### ISSUE TITLE
How to install this offline?

### ISSUE THREAD

**Issue by phanindrakalva** [Gallore/yaml_cli#7]
I'm trying to deploy this package on a server where there is no internet and root access. How to install this in such an environment?

**Comment by andywerner** [comment]
Use the "Download ZIP" button in GitHub to download the repo as ZIP file. Then run
`pip install yaml_cli-master.zip`

**Comment by phanindrakalva** [comment]
I tried it but didn't work for me. It is still trying to download from internet

pip install yaml_cli-master.zip
Processing ./yaml_cli-master.zip
Requirement already satisfied: PyYAML in /home/phani/.local/lib/python2.7/site-packages (from yaml-cli==0.0.7) (3.12)
Collecting argparse (from yaml-cli==0.0.7)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcf927bbe50>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/argparse/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcf927bb750>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/argparse/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcf927bb790>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/argparse/

**Comment by phanindrakalva** [comment]
nvm, after installing argparse it worked. Thanks

**Comment by andywerner** [comment]
Yes, thanks. 

You need to download and install argparse first: https://pypi.org/project/argparse/

Then download yaml_cli and install it like this:
`pip install yaml_cli-master.zip`
